# ===========================================================================
#
#                            PUBLIC DOMAIN NOTICE
#               National Center for Biotechnology Information
#
#  This software/database is a "United States Government Work" under the
#  terms of the United States Copyright Act.  It was written as part of
#  the author's official duties as a United States Government employee and
#  thus cannot be copyrighted.  This software/database is freely available
#  to the public for use. The National Library of Medicine and the U.S.
#  Government have not placed any restriction on its use or reproduction.
#
#  Although all reasonable efforts have been taken to ensure the accuracy
#  and reliability of the software and data, the NLM and the U.S.
#  Government do not and cannot warrant the performance or results that
#  may be obtained by using this software or data. The NLM and the U.S.
#  Government disclaim all warranties, express or implied, including
#  warranties of performance, merchantability or fitness for any particular
#  purpose.
#
#  Please cite the author in any work or product based on this material.
#
# ===========================================================================


default: run_all

clean:

.PHONY: default clean

PYTHON ?= python3

NGS_EXAMPLES = \
	FragTest \
	AlignTest \
	AlignSliceTest \
	PileupTest \
	RefTest

# ===========================================================================
#
# example runs
#

SETUP ?= NGS_PY_LIBRARY_PATH=../../lib64

run_frag:
	$(SETUP) $(PYTHON) FragTest.py ERR225922 10000 2 $(REDIRECT)

run_align:
	$(SETUP) $(PYTHON) AlignTest.py ERR225922 10000 2 $(REDIRECT)

run_align_slice:
	$(SETUP) $(PYTHON) AlignSliceTest.py SRR1121656 1 1 9999 $(REDIRECT)

run_pileup:
	$(SETUP) $(PYTHON) PileupTest.py SRR1121656 1 9999 10003 $(REDIRECT)

run_ref:
	$(SETUP) $(PYTHON) RefTest.py SRR1121656 $(REDIRECT)

ALL_TESTS = run_frag run_align run_align_slice run_pileup run_ref

run_all: $(ALL_TESTS)

.PHONY: run_all $(ALL_TESTS)

run_and_diff: expected.txt
	rm -f actual.txt; $(MAKE) run_all REDIRECT=">>actual.txt" ; \
	diff expected.txt actual.txt && rm actual.txt && echo NGS Python examples work as expected

.PHONY: run_and_diff