<QC>
  <current>
    <algorithm>'SHA-256'</algorithm>
    <digest>'94a62d388e037ea922a6a87a565b3293a26bae272dd5ff5b3efdb69db9869878'</digest>
    <fingerprint>
      '{&quot;maximum-position&quot;:8,&quot;A&quot;:[2,2,0,0,0,0,0,0,0],&quot;C&quot;:[0,0,1,0,1,1,0,0,0],&quot;G&quot;:[0,0,0,1,0,0,1,1,0],&quot;T&quot;:[0,0,1,1,1,0,1,0,0],&quot;N&quot;:[2,2,2,2,1,2,1,1,0],&quot;EoR&quot;:[0,0,0,0,1,0,0,1,2]}'
    </fingerprint>
    <format>'json utf-8 compact'</format>
    <version>'1.0.0'</version>
  </current>
  <history>
    <event_1>
      <added>
        <algorithm>'SHA-256'</algorithm>
        <digest>'98e287bd644e987873066e379a842926b6853d6447fee01821e958bee726e39c'</digest>
        <fingerprint>
          '{&quot;maximum-position&quot;:8,&quot;A&quot;:[0,0,0,0,0,0,0,0,0],&quot;C&quot;:[0,0,0,0,0,0,0,0,0],&quot;G&quot;:[0,0,0,0,0,0,0,0,0],&quot;T&quot;:[0,0,0,0,0,0,0,0,0],&quot;N&quot;:[2,2,2,2,1,1,1,1,0],&quot;EoR&quot;:[0,0,0,0,1,0,0,0,1]}'
        </fingerprint>
        <format>'json utf-8 compact'</format>
        <version>'1.0.0'</version>
      </added>
      <original>
        <algorithm>'SHA-256'</algorithm>
        <digest>'858fee7fd1220acf4d89cffe5a22ee0ea3f547e6636dafa6c240f3ea6ce5b08e'</digest>
        <fingerprint>
          '{&quot;maximum-position&quot;:8,&quot;A&quot;:[2,3,0,2,0,1,0,1,0],&quot;C&quot;:[0,1,1,0,1,1,0,0,0],&quot;G&quot;:[1,0,0,1,0,0,1,1,0],&quot;T&quot;:[1,0,3,1,2,0,2,0,0],&quot;N&quot;:[0,0,0,0,0,1,0,0,0],&quot;EoR&quot;:[0,0,0,0,1,0,0,1,2]}'
        </fingerprint>
        <format>'json utf-8 compact'</format>
        <version>'1.0.0'</version>
      </original>
      <reason>'REDACTION'</reason>
      <removed>
        <algorithm>'SHA-256'</algorithm>
        <digest>'4bd5773f5f1333325a7ce2dec4f5d0398987148f17709104e4115711f3ad90c9'</digest>
        <fingerprint>
          '{&quot;maximum-position&quot;:8,&quot;A&quot;:[0,1,0,2,0,1,0,1,0],&quot;C&quot;:[0,1,0,0,0,0,0,0,0],&quot;G&quot;:[1,0,0,0,0,0,0,0,0],&quot;T&quot;:[1,0,2,0,1,0,1,0,0],&quot;N&quot;:[0,0,0,0,0,0,0,0,0],&quot;EoR&quot;:[0,0,0,0,1,0,0,0,1]}'
        </fingerprint>
        <format>'json utf-8 compact'</format>
        <version>'1.0.0'</version>
      </removed>
    </event_1>
  </history>
</QC>
