<QC>
  <current>
    <algorithm>'SHA-256'</algorithm>
    <digest>'2638e72202baed9d97a041ac4d1af35433f1980230c065a71432e2210cbc707d'</digest>
    <fingerprint>
      '{&quot;maximum-position&quot;:4,&quot;A&quot;:[0,1,0,0,0],&quot;C&quot;:[1,0,0,0,0],&quot;G&quot;:[0,0,0,1,0],&quot;T&quot;:[0,0,1,0,0],&quot;N&quot;:[1,1,1,1,0],&quot;EoR&quot;:[0,0,0,0,2]}'
    </fingerprint>
    <format>'json utf-8 compact'</format>
    <version>'1.0.0'</version>
  </current>
  <history>
    <event_1>
      <added>
        <algorithm>'SHA-256'</algorithm>
        <digest>'fa634a63fb6ac40afba7ef9ecac792d4e062e81518dfd16c5a99f0a3731641b4'</digest>
        <fingerprint>
          '{&quot;maximum-position&quot;:4,&quot;A&quot;:[0,0,0,0,0],&quot;C&quot;:[0,0,0,0,0],&quot;G&quot;:[0,0,0,0,0],&quot;T&quot;:[0,0,0,0,0],&quot;N&quot;:[1,1,1,1,0],&quot;EoR&quot;:[0,0,0,0,1]}'
        </fingerprint>
        <format>'json utf-8 compact'</format>
        <version>'1.0.0'</version>
      </added>
      <original>
        <algorithm>'SHA-256'</algorithm>
        <digest>'67e4aef5339fee30de2f22d909494e19cffeefd900ba150bd0ed2ecf187879c5'</digest>
        <fingerprint>
          '{&quot;maximum-position&quot;:4,&quot;A&quot;:[0,1,1,0,0],&quot;C&quot;:[1,1,0,0,0],&quot;G&quot;:[1,0,0,1,0],&quot;T&quot;:[0,0,1,1,0],&quot;N&quot;:[0,0,0,0,0],&quot;EoR&quot;:[0,0,0,0,2]}'
        </fingerprint>
        <format>'json utf-8 compact'</format>
        <version>'1.0.0'</version>
      </original>
      <reason>'REDACTION'</reason>
      <removed>
        <algorithm>'SHA-256'</algorithm>
        <digest>'6cc6fa678d9a7717ff7b02185c46f0d0875cbe7a597db39bc975bceae1ec2e16'</digest>
        <fingerprint>
          '{&quot;maximum-position&quot;:4,&quot;A&quot;:[0,0,1,0,0],&quot;C&quot;:[0,1,0,0,0],&quot;G&quot;:[1,0,0,0,0],&quot;T&quot;:[0,0,0,1,0],&quot;N&quot;:[0,0,0,0,0],&quot;EoR&quot;:[0,0,0,0,1]}'
        </fingerprint>
        <format>'json utf-8 compact'</format>
        <version>'1.0.0'</version>
      </removed>
    </event_1>
  </history>
</QC>
