/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_AlignmentIteratorItf */

#ifndef _Included_ngs_itf_AlignmentIteratorItf
#define _Included_ngs_itf_AlignmentIteratorItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_AlignmentIteratorItf
 * Method:    NextAlignment
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_AlignmentIteratorItf_NextAlignment
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
