/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_PileupIteratorItf */

#ifndef _Included_ngs_itf_PileupIteratorItf
#define _Included_ngs_itf_PileupIteratorItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_PileupIteratorItf
 * Method:    NextPileup
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_PileupIteratorItf_NextPileup
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
