/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_AlignmentItf */

#ifndef _Included_ngs_itf_AlignmentItf
#define _Included_ngs_itf_AlignmentItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetFragmentId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetFragmentId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetFragmentBases
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetFragmentBases
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetFragmentQualities
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetFragmentQualities
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    IsPaired
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_AlignmentItf_IsPaired
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetAlignmentId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetAlignmentId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetReferenceSpec
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetReferenceSpec
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetMappingQuality
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ngs_itf_AlignmentItf_GetMappingQuality
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetReferenceBases
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetReferenceBases
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetReadGroup
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetReadGroup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetReadId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetReadId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetClippedFragmentBases
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetClippedFragmentBases
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetClippedFragmentQualities
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetClippedFragmentQualities
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetAlignedFragmentBases
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetAlignedFragmentBases
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetAlignmentCategory
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ngs_itf_AlignmentItf_GetAlignmentCategory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetAlignmentPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_AlignmentItf_GetAlignmentPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetAlignmentLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_AlignmentItf_GetAlignmentLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetIsReversedOrientation
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_AlignmentItf_GetIsReversedOrientation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetSoftClip
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_ngs_itf_AlignmentItf_GetSoftClip
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetTemplateLength
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_AlignmentItf_GetTemplateLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetShortCigar
 * Signature: (JZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetShortCigar
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetLongCigar
 * Signature: (JZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetLongCigar
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetRNAOrientation
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_ngs_itf_AlignmentItf_GetRNAOrientation
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    HasMate
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_AlignmentItf_HasMate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetMateAlignmentId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetMateAlignmentId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetMateAlignment
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_AlignmentItf_GetMateAlignment
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetMateReferenceSpec
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_AlignmentItf_GetMateReferenceSpec
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_AlignmentItf
 * Method:    GetMateIsReversedOrientation
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_AlignmentItf_GetMateIsReversedOrientation
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
