mv ./build/.cvsignore                        ./build/.gitignore
mv ./build/Xcode/old-toolkit/.cvsignore      ./build/Xcode/old-toolkit/.gitignore
mv ./tools/align-info/.cvsignore             ./tools/align-info/.gitignore
mv ./tools/.cvsignore                        ./tools/.gitignore
mv ./tools/bam-loader/.cvsignore             ./tools/bam-loader/.gitignore
mv ./tools/ccextract/.cvsignore              ./tools/ccextract/.gitignore
mv ./tools/cg-load/.cvsignore                ./tools/cg-load/.gitignore
mv ./tools/check-blob-size/.cvsignore        ./tools/check-blob-size/.gitignore
mv ./tools/copycat/.cvsignore                ./tools/copycat/.gitignore
mv ./tools/deseq/.cvsignore                  ./tools/deseq/.gitignore
mv ./tools/fastq-loader/.cvsignore           ./tools/fastq-loader/.gitignore
mv ./tools/fix-run-stat/.cvsignore           ./tools/fix-run-stat/.gitignore
mv ./tools/kar/.cvsignore                    ./tools/kar/.gitignore
mv ./tools/kqsh/.cvsignore                   ./tools/kqsh/.gitignore
mv ./tools/meta-sync/.cvsignore              ./tools/meta-sync/.gitignore
mv ./tools/nenctool/.cvsignore               ./tools/nenctool/.gitignore
mv ./tools/nencvalid/.cvsignore              ./tools/nencvalid/.gitignore
mv ./tools/pacbio-load/.cvsignore            ./tools/pacbio-load/.gitignore
mv ./tools/qual-recalib-stat/.cvsignore      ./tools/qual-recalib-stat/.gitignore
mv ./tools/rd-filter-redact/.cvsignore       ./tools/rd-filter-redact/.gitignore
mv ./tools/refseq-load/.cvsignore            ./tools/refseq-load/.gitignore
mv ./tools/run-stat/.cvsignore               ./tools/run-stat/.gitignore
mv ./tools/sam-dump/.cvsignore               ./tools/sam-dump/.gitignore
mv ./tools/sra/.cvsignore                    ./tools/sra/.gitignore
mv ./tools/sra-dbcc/.cvsignore               ./tools/sra-dbcc/.gitignore
mv ./tools/sra-dump/.cvsignore               ./tools/sra-dump/.gitignore
mv ./tools/sra-load/.cvsignore               ./tools/sra-load/.gitignore
mv ./tools/sra-pileup/.cvsignore             ./tools/sra-pileup/.gitignore
mv ./tools/sra-stat/.cvsignore               ./tools/sra-stat/.gitignore
mv ./tools/srapath/.cvsignore                ./tools/srapath/.gitignore
mv ./tools/update-schema/.cvsignore          ./tools/update-schema/.gitignore
mv ./tools/util/.cvsignore                   ./tools/util/.gitignore
mv ./tools/varloc-load/.cvsignore            ./tools/varloc-load/.gitignore
mv ./tools/vdb-config/.cvsignore             ./tools/vdb-config/.gitignore
mv ./tools/vdb-copy/.cvsignore               ./tools/vdb-copy/.gitignore
mv ./tools/vdb-dump/.cvsignore               ./tools/vdb-dump/.gitignore
mv ./tools/vdb-validate/.cvsignore           ./tools/vdb-validate/.gitignore
mv ./tools/vtblcp/.cvsignore                 ./tools/vtblcp/.gitignore
mv ./tools/workspace/.cvsignore              ./tools/workspace/.gitignore
mv ./.cvsignore                              ./.gitignore
