/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_ReadGroupIteratorItf */

#ifndef _Included_ngs_itf_ReadGroupIteratorItf
#define _Included_ngs_itf_ReadGroupIteratorItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_ReadGroupIteratorItf
 * Method:    NextReadGroup
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_ReadGroupIteratorItf_NextReadGroup
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
