/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_PileupEventIteratorItf */

#ifndef _Included_ngs_itf_PileupEventIteratorItf
#define _Included_ngs_itf_PileupEventIteratorItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_PileupEventIteratorItf
 * Method:    NextPileupEvent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_PileupEventIteratorItf_NextPileupEvent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_PileupEventIteratorItf
 * Method:    ResetPileupEvent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ngs_itf_PileupEventIteratorItf_ResetPileupEvent
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
