/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_FragmentIteratorItf */

#ifndef _Included_ngs_itf_FragmentIteratorItf
#define _Included_ngs_itf_FragmentIteratorItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_FragmentIteratorItf
 * Method:    NextFragment
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_FragmentIteratorItf_NextFragment
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
