/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_ReferenceIteratorItf */

#ifndef _Included_ngs_itf_ReferenceIteratorItf
#define _Included_ngs_itf_ReferenceIteratorItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_ReferenceIteratorItf
 * Method:    NextReference
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_ReferenceIteratorItf_NextReference
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
