/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_FragmentItf */

#ifndef _Included_ngs_itf_FragmentItf
#define _Included_ngs_itf_FragmentItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_FragmentItf
 * Method:    GetFragmentId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_FragmentItf_GetFragmentId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_FragmentItf
 * Method:    GetFragmentBases
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_FragmentItf_GetFragmentBases
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ngs_itf_FragmentItf
 * Method:    GetFragmentQualities
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_FragmentItf_GetFragmentQualities
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ngs_itf_FragmentItf
 * Method:    IsPaired
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_FragmentItf_IsPaired
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_FragmentItf
 * Method:    IsAligned
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_FragmentItf_IsAligned
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
