/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_Package */

#ifndef _Included_ngs_Package
#define _Included_ngs_Package
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_Package
 * Method:    GetPackageVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_Package_GetPackageVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
