/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_ReadIteratorItf */

#ifndef _Included_ngs_itf_ReadIteratorItf
#define _Included_ngs_itf_ReadIteratorItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_ReadIteratorItf
 * Method:    NextRead
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_ReadIteratorItf_NextRead
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
