/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_ReadGroupItf */

#ifndef _Included_ngs_itf_ReadGroupItf
#define _Included_ngs_itf_ReadGroupItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_ReadGroupItf
 * Method:    GetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_ReadGroupItf_GetName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_ReadGroupItf
 * Method:    GetStatistics
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_ReadGroupItf_GetStatistics
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
