/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_ReadItf */

#ifndef _Included_ngs_itf_ReadItf
#define _Included_ngs_itf_ReadItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_ReadItf
 * Method:    GetFragmentId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_ReadItf_GetFragmentId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    GetFragmentBases
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_ReadItf_GetFragmentBases
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    GetFragmentQualities
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_ReadItf_GetFragmentQualities
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    IsPaired
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_ReadItf_IsPaired
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    IsAligned
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_ReadItf_IsAligned
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    NextFragment
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_ReadItf_NextFragment
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    GetReadId
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_ReadItf_GetReadId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    GetNumFragments
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ngs_itf_ReadItf_GetNumFragments
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    FragmentIsAligned
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_ngs_itf_ReadItf_FragmentIsAligned
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    GetReadCategory
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ngs_itf_ReadItf_GetReadCategory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    GetReadGroup
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_ReadItf_GetReadGroup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    GetReadName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_ReadItf_GetReadName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    GetReadBases
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_ReadItf_GetReadBases
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ngs_itf_ReadItf
 * Method:    GetReadQualities
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_ReadItf_GetReadQualities
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
