/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ngs_itf_StatisticsItf */

#ifndef _Included_ngs_itf_StatisticsItf
#define _Included_ngs_itf_StatisticsItf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ngs_itf_StatisticsItf
 * Method:    GetValueType
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ngs_itf_StatisticsItf_GetValueType
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ngs_itf_StatisticsItf
 * Method:    GetAsString
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_StatisticsItf_GetAsString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ngs_itf_StatisticsItf
 * Method:    GetAsI64
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_StatisticsItf_GetAsI64
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ngs_itf_StatisticsItf
 * Method:    GetAsU64
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ngs_itf_StatisticsItf_GetAsU64
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ngs_itf_StatisticsItf
 * Method:    GetAsDouble
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_ngs_itf_StatisticsItf_GetAsDouble
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ngs_itf_StatisticsItf
 * Method:    NextPath
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ngs_itf_StatisticsItf_NextPath
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
