# ===========================================================================
#
#                            PUBLIC DOMAIN NOTICE
#               National Center for Biotechnology Information
#
#  This software/database is a "United States Government Work" under the
#  terms of the United States Copyright Act.  It was written as part of
#  the author's official duties as a United States Government employee and
#  thus cannot be copyrighted.  This software/database is freely available
#  to the public for use. The National Library of Medicine and the U.S.
#  Government have not placed any restriction on its use or reproduction.
#
#  Although all reasonable efforts have been taken to ensure the accuracy
#  and reliability of the software and data, the NLM and the U.S.
#  Government do not and cannot warrant the performance or results that
#  may be obtained by using this software or data. The NLM and the U.S.
#  Government disclaim all warranties, express or implied, including
#  warranties of performance, merchantability or fitness for any particular
#  purpose.
#
#  Please cite the author in any work or product based on this material.
#
# ===========================================================================


# All of this section is to provide semi-automatic detection of
# required libraries and headers. They SHOULD have been built and installed
# already before building these examples.

NCBI_VDB_LIBDIR ?= $(abspath ../../../ncbi-vdb/lib64)
NCBI_VDB_INCDIR ?= $(abspath ../../../ncbi-vdb/include)
NGS_LIBDIR      ?= $(abspath ../../lib64)
NGS_INCDIR      ?= $(abspath ../../include)

# $(warning NCBI_VDB_LIBDIR=$(NCBI_VDB_LIBDIR))
# $(warning NCBI_VDB_INCDIR=$(NCBI_VDB_INCDIR))
# $(warning NGS_LIBDIR=$(NGS_LIBDIR))
# $(warning NGS_INCDIR=$(NGS_INCDIR))

ifeq (,$(wildcard $(NCBI_VDB_INCDIR)))

ncbi-headers:
	@ echo "NCBI_VDB headers are not found (looking for $(NCBI_VDB_INCDIR))"
	@ false

else

CPPFLAGS += -I$(NCBI_VDB_INCDIR)
ncbi-headers:
	@ true

endif

ifeq (,$(wildcard $(NGS_INCDIR)))

ngs-headers:
	@ echo "NGS headers are not found (looking for $(NGS_INCDIR))"
	@ false

else

CPPFLAGS += -I$(NGS_INCDIR)
ngs-headers:
	@ true

endif

.PHONY: ncbi-headers ngs-headers
